CREATE TABLE IF NOT EXISTS ai.tenants (id text PRIMARY KEY, name text NOT NULL, status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','suspended','deleted')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ai.companies (id text PRIMARY KEY, tenant_id text NOT NULL REFERENCES ai.tenants(id), name text NOT NULL, status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','archived')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (tenant_id, id));
CREATE TABLE IF NOT EXISTS ai.users (id text PRIMARY KEY, email text NOT NULL UNIQUE, full_name text, status text NOT NULL DEFAULT 'active' CHECK (status IN ('invited','active','suspended','revoked')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ai.memberships (id text PRIMARY KEY, user_id text NOT NULL REFERENCES ai.users(id), tenant_id text NOT NULL REFERENCES ai.tenants(id), company_id text, role text NOT NULL CHECK (role IN ('platform_superadmin','tenant_owner','tenant_admin','company_admin','executive','analyst','viewer','ai_worker')), status text NOT NULL DEFAULT 'active' CHECK (status IN ('invited','active','suspended','revoked')), version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (user_id, tenant_id, company_id), FOREIGN KEY (tenant_id, company_id) REFERENCES ai.companies(tenant_id, id));
CREATE INDEX IF NOT EXISTS memberships_scope_idx ON ai.memberships (tenant_id, company_id, status, role);
CREATE INDEX IF NOT EXISTS memberships_user_idx ON ai.memberships (user_id, tenant_id, status);
CREATE TABLE IF NOT EXISTS ai.access_audit_events (id text PRIMARY KEY, actor_id text, actor_type text NOT NULL, tenant_id text, company_id text, action text NOT NULL, outcome text NOT NULL CHECK (outcome IN ('allowed','denied')), request_id text, metadata_jsonb jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS access_audit_scope_idx ON ai.access_audit_events (tenant_id, company_id, created_at DESC);
CREATE TABLE IF NOT EXISTS ai.platform_operators (id text PRIMARY KEY, user_id text NOT NULL UNIQUE, role text NOT NULL CHECK (role = 'platform_superadmin'), status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','suspended','revoked')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
