const CITED = {
  type: "object", additionalProperties: false, required: ["text", "source_claim_ids"],
  properties: { text: { type: "string", minLength: 1, maxLength: 1200 }, source_claim_ids: { type: "array", minItems: 1, maxItems: 12, items: { type: "string", minLength: 1, maxLength: 64 } } },
};
const POINT_GROUP = {
  type: "object", additionalProperties: false, required: ["report_item_id", "issue_id", "group", "title", "priority", "status", "what_happened", "why_important", "impact", "risk", "watch", "source_claim_ids"],
  properties: {
    report_item_id: { type: "string", minLength: 1, maxLength: 64 }, issue_id: { type: "string", minLength: 1, maxLength: 64 }, group: { type: "string", enum: ["important_today", "new", "developing", "closed"] }, title: { type: "string", minLength: 1, maxLength: 180 }, priority: { type: "string", enum: ["tinggi", "sedang", "rendah"] }, status: { type: "string", enum: ["baru", "berkembang", "dipantau", "selesai"] },
    what_happened: { type: "array", minItems: 1, maxItems: 6, items: { type: "string", minLength: 1, maxLength: 500 } }, why_important: { type: "array", minItems: 1, maxItems: 6, items: { type: "string", minLength: 1, maxLength: 500 } }, impact: { type: "array", minItems: 1, maxItems: 6, items: { type: "string", minLength: 1, maxLength: 500 } }, risk: { type: "array", minItems: 0, maxItems: 6, items: { type: "string", minLength: 1, maxLength: 500 } }, watch: { type: "array", minItems: 0, maxItems: 6, items: { type: "string", minLength: 1, maxLength: 500 } }, source_claim_ids: { type: "array", minItems: 1, maxItems: 12, items: { type: "string", minLength: 1, maxLength: 64 } },
  },
};
const IMPACT = { type: "object", additionalProperties: false, required: ["category", "points", "source_claim_ids"], properties: { category: { type: "string", minLength: 1, maxLength: 80 }, points: { type: "array", minItems: 1, maxItems: 8, items: { type: "string", minLength: 1, maxLength: 500 } }, source_claim_ids: { type: "array", minItems: 1, maxItems: 12, items: { type: "string", minLength: 1, maxLength: 64 } } } };
const RISK_OPPORTUNITY = { type: "object", additionalProperties: false, required: ["kind", "title", "text", "source_claim_ids"], properties: { kind: { type: "string", enum: ["risk", "opportunity", "assumption"] }, title: { type: "string", minLength: 1, maxLength: 180 }, text: { type: "string", minLength: 1, maxLength: 800 }, source_claim_ids: { type: "array", minItems: 1, maxItems: 12, items: { type: "string", minLength: 1, maxLength: 64 } } } };
const CATEGORY = { type: "object", additionalProperties: false, required: ["category", "title", "points", "impact", "source_claim_ids"], properties: { category: { type: "string", minLength: 1, maxLength: 80 }, title: { type: "string", minLength: 1, maxLength: 180 }, points: { type: "array", minItems: 1, maxItems: 8, items: { type: "string", minLength: 1, maxLength: 500 } }, impact: { type: "array", minItems: 0, maxItems: 6, items: { type: "string", minLength: 1, maxLength: 500 } }, source_claim_ids: { type: "array", minItems: 1, maxItems: 12, items: { type: "string", minLength: 1, maxLength: 64 } } } };
const COMPARISON = { type: "object", additionalProperties: false, required: ["label", "new_items", "worsened", "improved", "priority_shifts", "source_claim_ids"], properties: { label: { type: "string", minLength: 1, maxLength: 160 }, new_items: { type: "array", maxItems: 12, items: { type: "string", minLength: 1, maxLength: 500 } }, worsened: { type: "array", maxItems: 12, items: { type: "string", minLength: 1, maxLength: 500 } }, improved: { type: "array", maxItems: 12, items: { type: "string", minLength: 1, maxLength: 500 } }, priority_shifts: { type: "array", maxItems: 12, items: { type: "string", minLength: 1, maxLength: 500 } }, source_claim_ids: { type: "array", minItems: 0, maxItems: 24, items: { type: "string", minLength: 1, maxLength: 64 } } } };
const T13_OUTPUT_SCHEMA = Object.freeze({ name: "report_narrative_v2", schema: { type: "object", additionalProperties: false, required: ["report_type", "executive_summary", "overview", "issue_sections", "category_developments", "comparison", "trends", "company_impacts", "risk_opportunity", "watch_items", "follow_up_options", "source_references"], properties: {
  report_type: { type: "string", enum: ["harian", "mingguan", "bulanan"] }, executive_summary: { type: "array", minItems: 3, maxItems: 5, items: { type: "string", minLength: 1, maxLength: 500 } }, overview: { type: "array", minItems: 0, maxItems: 8, items: CITED }, issue_sections: { type: "array", minItems: 0, maxItems: 20, items: POINT_GROUP }, category_developments: { type: "array", minItems: 0, maxItems: 8, items: CATEGORY }, comparison: COMPARISON, trends: { type: "array", minItems: 0, maxItems: 10, items: CITED }, company_impacts: { type: "array", minItems: 0, maxItems: 8, items: IMPACT }, risk_opportunity: { type: "array", minItems: 1, maxItems: 20, items: RISK_OPPORTUNITY }, watch_items: { type: "array", minItems: 0, maxItems: 12, items: CITED }, follow_up_options: { type: "array", minItems: 0, maxItems: 10, items: CITED }, source_references: { type: "array", minItems: 1, maxItems: 80, items: { type: "object", additionalProperties: false, required: ["claim_id", "source_article_id"], properties: { claim_id: { type: "string", minLength: 1, maxLength: 64 }, source_article_id: { type: "string", minLength: 1, maxLength: 160 } } } },
} } });
module.exports = { T13_OUTPUT_SCHEMA };
