class AiPipelineWorker {
  constructor({ queue, registry, stateStore, workerId = "ai-worker" } = {}) { if (!queue?.enqueue || !queue?.processNext) throw new TypeError("AI pipeline worker requires a queue service"); if (!registry?.get) throw new TypeError("AI pipeline worker requires a task registry"); if (!stateStore?.get || !stateStore?.claim || !stateStore?.complete || !stateStore?.fail) throw new TypeError("AI pipeline worker requires pipeline state persistence"); Object.assign(this, { queue, registry, stateStore, workerId }); }
  enqueueTask({ tenantId, companyId, pipelineId, taskId, expectedStateVersion, input = {}, nextTaskId = null }) { const task = this.registry.get(taskId); if (nextTaskId && !this.registry.get(nextTaskId)) throw configurationError("Next AI task is not registered"); return this.queue.enqueue({ tenantId, companyId, queueName: `ai-task-${taskId}`, jobType: taskId, idempotencyKey: `pipeline-${pipelineId}-${taskId}-${expectedStateVersion}`, payload: { pipeline_id: pipelineId, task_id: taskId, expected_state_version: expectedStateVersion, input: structuredClone(input), model: task.model, next_task_id: nextTaskId }, maxAttempts: 3 }); }
  async processNext({ taskId }) { const task = this.registry.get(taskId); return this.queue.processNext({ queueName: `ai-task-${taskId}`, workerId: `${this.workerId}-${taskId}`, handler: (job) => this._execute(task, job) }); }
  async _execute(task, job) { const payload = job.payload; if (payload.task_id !== task.taskId || payload.model !== task.model) throw configurationError("AI task model routing mismatch"); const current = this.stateStore.get({ tenantId: job.tenantId, companyId: job.companyId, pipelineId: payload.pipeline_id }); const expectedStateVersion = current?.status === "retrying" ? current.version : payload.expected_state_version; const before = this.stateStore.claim({ tenantId: job.tenantId, companyId: job.companyId, pipelineId: payload.pipeline_id, taskId: task.taskId, expectedVersion: expectedStateVersion }); try { const output = await task.handler({ tenantId: job.tenantId, companyId: job.companyId, pipelineId: payload.pipeline_id, taskId: task.taskId, model: task.model, input: payload.input, state: before }); const after = this.stateStore.complete({ tenantId: job.tenantId, companyId: job.companyId, pipelineId: payload.pipeline_id, taskId: task.taskId, expectedVersion: before.version, nextTaskId: payload.next_task_id || null }); let nextJob = null; if (payload.next_task_id) nextJob = this.enqueueTask({ tenantId: job.tenantId, companyId: job.companyId, pipelineId: payload.pipeline_id, taskId: payload.next_task_id, expectedStateVersion: after.version, input: output?.nextInput || {}, nextTaskId: output?.nextTaskId || null }); return { output, state: after, nextJob }; } catch (error) { const retrying = job.attempts < job.maxAttempts && (error?.retryable === true || ["ETIMEDOUT", "ECONNRESET", "EAI_AGAIN"].includes(error?.code)); this.stateStore.fail({ tenantId: job.tenantId, companyId: job.companyId, pipelineId: payload.pipeline_id, taskId: task.taskId, expectedVersion: before.version, status: retrying ? "retrying" : "dead_letter", errorCode: error?.code || "AI_TASK_FAILED", errorMessage: safeMessage(error) }); throw error; } }
}
function safeMessage(error) { return typeof error?.message === "string" && error.message.length <= 500 ? error.message : "AI task failed"; }
function configurationError(message) { const error = new Error(message); error.code = "AI_TASK_CONFIGURATION_INVALID"; error.statusCode = 503; return error; }
module.exports = { AiPipelineWorker };
