const { randomUUID } = require("crypto");
const ALLOWED_NEXT = Object.freeze({ INGEST: new Set(["T02"]), T01: new Set([]), T02: new Set(["T03"]), T03: new Set(["T04"]), T04: new Set(["T05"]), T05: new Set(["T06"]), T06: new Set(["T07"]), T07: new Set(["T08"]), T08: new Set(["T09"]), T09: new Set(["T10"]), T10: new Set(["T12", "T13"]), T12: new Set([]), T13: new Set([]), T14: new Set([]) });
class InMemoryPipelineStateStore {
  constructor({ uuid = randomUUID, now = Date.now } = {}) { this.uuid = uuid; this.now = now; this.states = new Map(); }
  create({ tenantId, companyId, pipelineId = this.uuid(), currentTaskId = "INGEST" }) { if (this.states.has(pipelineId)) return clone(this.states.get(pipelineId)); const value = { pipelineId, tenantId, companyId, currentTaskId, status: "queued", version: 1, lastErrorCode: null, lastErrorMessage: null, createdAt: timestamp(this.now), updatedAt: timestamp(this.now) }; this.states.set(pipelineId, value); return clone(value); }
  get({ tenantId, companyId, pipelineId }) { const value = this.states.get(pipelineId); return value && value.tenantId === tenantId && value.companyId === companyId ? clone(value) : null; }
  claim({ tenantId, companyId, pipelineId, taskId, expectedVersion }) { const value = this._scope({ tenantId, companyId, pipelineId }); if (value.currentTaskId !== taskId || value.version !== expectedVersion || !["queued", "retrying"].includes(value.status)) throw stateError("Pipeline task state/version conflict"); value.status = "running"; value.version += 1; value.updatedAt = timestamp(this.now); return clone(value); }
  complete({ tenantId, companyId, pipelineId, taskId, expectedVersion, nextTaskId = null }) { const value = this._scope({ tenantId, companyId, pipelineId }); if (value.currentTaskId !== taskId || value.version !== expectedVersion || value.status !== "running") throw stateError("Pipeline completion state/version conflict"); if (nextTaskId && !ALLOWED_NEXT[taskId]?.has(nextTaskId)) throw stateError(`Invalid pipeline transition ${taskId} -> ${nextTaskId}`); value.currentTaskId = nextTaskId; value.status = nextTaskId ? "queued" : "succeeded"; value.version += 1; value.lastErrorCode = null; value.lastErrorMessage = null; value.updatedAt = timestamp(this.now); return clone(value); }
  fail({ tenantId, companyId, pipelineId, taskId, expectedVersion, status, errorCode, errorMessage }) { const value = this._scope({ tenantId, companyId, pipelineId }); if (value.currentTaskId !== taskId || value.version !== expectedVersion || value.status !== "running") throw stateError("Pipeline failure state/version conflict"); value.status = status; value.lastErrorCode = errorCode; value.lastErrorMessage = errorMessage; value.version += 1; value.updatedAt = timestamp(this.now); return clone(value); }
  _scope(input) { const value = this.states.get(input.pipelineId); if (!value || value.tenantId !== input.tenantId || value.companyId !== input.companyId) throw stateError("Pipeline state is outside tenant/company scope"); return value; }
}
function timestamp(now) { return new Date(now()).toISOString(); }
function stateError(message) { const error = new Error(message); error.code = "PIPELINE_STATE_CONFLICT"; error.statusCode = 409; return error; }
function clone(value) { return structuredClone(value); }
module.exports = { InMemoryPipelineStateStore, ALLOWED_NEXT };
