const { InMemoryJobStore } = require("./job.store");
class JobQueueService {
  constructor({ jobStore = new InMemoryJobStore(), now = Date.now, workerId = "worker-default", backoff = defaultBackoff, isRetryable = defaultRetryable } = {}) { this.jobStore = jobStore; this.now = now; this.workerId = workerId; this.backoff = backoff; this.isRetryable = isRetryable; }
  enqueue({ tenantId, companyId, queueName, jobType, idempotencyKey, payload = {}, maxAttempts = 3, availableAt = this.now() }) { if (![tenantId, companyId, queueName, jobType, idempotencyKey].every((value) => typeof value === "string" && value.trim())) throw validationError("Queue job scope, type, and idempotency key are required"); if (idempotencyKey.length < 16 || idempotencyKey.length > 255) throw validationError("Queue idempotency key must be 16 to 255 characters"); if (!payload || typeof payload !== "object" || Array.isArray(payload)) throw validationError("Queue job payload must be an object"); if (!Number.isInteger(maxAttempts) || maxAttempts < 1 || maxAttempts > 10) throw validationError("Queue max attempts must be from 1 to 10"); return this.jobStore.createOrGet({ tenantId, companyId, queueName, jobType, idempotencyKey, payload, maxAttempts, availableAt }); }
  async processNext({ queueName, handler, workerId = this.workerId } = {}) { if (typeof queueName !== "string" || typeof handler !== "function") throw validationError("Queue name and handler are required"); const job = this.jobStore.claimNext({ queueName, workerId, now: this.now() }); if (!job) return null; try { const result = await handler(job); return { job: this.jobStore.complete({ jobId: job.jobId, workerId }), result }; } catch (error) { const errorCode = typeof error?.code === "string" ? error.code : "JOB_FAILED"; const errorMessage = safeErrorMessage(error); if (this.isRetryable(error) && job.attempts < job.maxAttempts) { const delayMs = this.backoff({ attempt: job.attempts, job, error }); return { job: this.jobStore.retry({ jobId: job.jobId, workerId, availableAt: this.now() + delayMs, errorCode, errorMessage }), retried: true, delayMs }; } return { job: this.jobStore.deadLetter({ jobId: job.jobId, workerId, errorCode, errorMessage }), retried: false, deadLettered: true }; } }
}
function defaultBackoff({ attempt }) { return Math.min(300000, 1000 * (2 ** Math.max(0, attempt - 1))); }
function defaultRetryable(error) { return error?.retryable === true || ["ETIMEDOUT", "ECONNRESET", "ECONNREFUSED", "EAI_AGAIN", "EHOSTUNREACH"].includes(error?.code); }
function safeErrorMessage(error) { return typeof error?.message === "string" && error.message.length <= 500 ? error.message : "Job handler failed"; }
function validationError(message) { const error = new Error(message); error.code = "VALIDATION_ERROR"; error.statusCode = 400; return error; }
module.exports = { JobQueueService, defaultBackoff, defaultRetryable };
