const { randomUUID } = require("node:crypto");
const { permissionsForRole, isRole } = require("./rbac");
class MembershipNotFoundError extends Error { constructor(message = "Membership was not found") { super(message); this.code = "FORBIDDEN"; this.statusCode = 403; } }
class InMemoryMembershipStore {
  constructor({ memberships = [], now = Date.now } = {}) { this.memberships = new Map(); this.users = new Map(); this.now = now; for (const membership of memberships) this.upsert(membership); }
  upsert(input) { if (!input?.userId || !input.tenantId || !isRole(input.role)) throw new TypeError("A membership requires user, tenant, and valid role"); const key = `${input.userId}:${input.tenantId}:${input.companyId || "*"}`; const value = { membershipId: input.membershipId || randomUUID(), userId: input.userId, tenantId: input.tenantId, companyId: input.companyId || null, role: input.role, status: input.status || "active", version: input.version || 1, updatedAt: new Date(this.now()).toISOString() }; this.memberships.set(key, value); return { ...value }; }
  async resolve({ userId, tenantId, companyId = null, actorType = "human" }) { const exact = companyId ? this._find(userId, tenantId, companyId) : null; const tenant = this._find(userId, tenantId, null); const membership = exact || tenant; if (!membership || membership.status !== "active") throw new MembershipNotFoundError(); return { ...membership, actorType, permissions: [...permissionsForRole(membership.role)] }; }
  async list({ tenantId, companyId = undefined, page = 1, limit = 50 }) { const values = [...this.memberships.values()].filter((item) => item.tenantId === tenantId && (companyId === undefined || item.companyId === companyId)); const start = (page - 1) * limit; return { items: values.slice(start, start + limit).map((item) => ({ ...item, permissions: [...permissionsForRole(item.role)] })), page, limit, total: values.length }; }
  async listForUser({ userId }) { return [...this.memberships.values()].filter((item) => item.userId === userId && item.status === "active").map((item) => ({ ...item, permissions: [...permissionsForRole(item.role)] })); }
  async invite({ userId, email, fullName, tenantId, companyId = null, role, idempotencyKey }) { if (!userId && !email) throw new TypeError("userId or email is required"); const resolvedUserId = userId || `user:${email.toLowerCase()}`; this.users.set(resolvedUserId, { userId: resolvedUserId, email, fullName: fullName || null, status: "invited" }); return { membership: this.upsert({ userId: resolvedUserId, tenantId, companyId, role, status: "invited" }), reused: false, idempotencyKey }; }
  async activateByUser({ userId }) { const activated = []; for (const [key, membership] of this.memberships.entries()) if (membership.userId === userId && membership.status === "invited") { const next = { ...membership, status: "active", version: membership.version + 1, updatedAt: new Date(this.now()).toISOString() }; this.memberships.set(key, next); activated.push({ ...next, permissions: [...permissionsForRole(next.role)] }); } return activated; }
  async update({ membershipId, tenantId, role, companyId, status, expectedVersion }) { const key = [...this.memberships.keys()].find((item) => this.memberships.get(item).membershipId === membershipId && this.memberships.get(item).tenantId === tenantId); const current = key ? this.memberships.get(key) : null; if (!current) throw new MembershipNotFoundError(); if (current.version !== expectedVersion) return { conflict: { expectedVersion, actualVersion: current.version } }; this.memberships.delete(key); return { membership: this.upsert({ ...current, role: role || current.role, companyId: companyId === undefined ? current.companyId : companyId, status: status || current.status, version: current.version + 1 }), reused: false }; }
  async revoke({ membershipId, tenantId, expectedVersion }) { return this.update({ membershipId, tenantId, expectedVersion, status: "revoked" }); }
  _find(userId, tenantId, companyId) { return [...this.memberships.values()].find((item) => item.userId === userId && item.tenantId === tenantId && item.companyId === companyId); }
}
class PostgresMembershipStore {
  constructor({ db } = {}) { if (!db?.query) throw new TypeError("PostgresMembershipStore requires db"); this.db = db; }
  async resolve({ userId, tenantId, companyId = null, actorType = "human" }) { const result = await this.db.query(`SELECT m.id AS membership_id,m.user_id,m.tenant_id,m.company_id,m.role,m.status,m.version FROM ai.memberships m WHERE m.user_id=$1 AND m.tenant_id=$2 AND m.status='active' AND (m.company_id=$3 OR (m.company_id IS NULL AND $3 IS NOT NULL) OR (m.company_id IS NULL AND $3 IS NULL)) ORDER BY (m.company_id IS NULL) ASC LIMIT 1`, [userId, tenantId, companyId]); const row = result.rows[0]; if (!row) throw new MembershipNotFoundError(); return { membershipId: row.membership_id, userId: row.user_id, tenantId: row.tenant_id, companyId: row.company_id, role: row.role, status: row.status, version: row.version, actorType, permissions: [...permissionsForRole(row.role)] }; }
  async list({ tenantId, companyId = undefined, page = 1, limit = 50 }) { const values = [tenantId]; const filters = ["tenant_id=$1"]; if (companyId !== undefined) { values.push(companyId); filters.push(`company_id=$${values.length}`); } values.push(limit, (page - 1) * limit); const result = await this.db.query(`SELECT id AS membership_id,user_id,tenant_id,company_id,role,status,version FROM ai.memberships WHERE ${filters.join(" AND ")} ORDER BY created_at DESC LIMIT $${values.length - 1} OFFSET $${values.length}`, values); return { items: result.rows.map((row) => ({ membershipId: row.membership_id, userId: row.user_id, tenantId: row.tenant_id, companyId: row.company_id, role: row.role, status: row.status, version: row.version, permissions: [...permissionsForRole(row.role)] })), page, limit, total: result.rowCount }; }
  async listForUser({ userId }) { const result = await this.db.query("SELECT id AS membership_id,user_id,tenant_id,company_id,role,status,version FROM ai.memberships WHERE user_id=$1 AND status='active' ORDER BY created_at ASC", [userId]); return result.rows.map((row) => ({ membershipId: row.membership_id, userId: row.user_id, tenantId: row.tenant_id, companyId: row.company_id, role: row.role, status: row.status, version: row.version, permissions: [...permissionsForRole(row.role)] })); }
  async invite({ userId, email, fullName, tenantId, companyId = null, role }) { const resolvedUserId = userId || `user:${String(email).toLowerCase()}`; await this.db.query(`INSERT INTO ai.users (id,email,full_name,status) VALUES ($1,$2,$3,'invited') ON CONFLICT (email) DO UPDATE SET full_name=COALESCE(EXCLUDED.full_name,ai.users.full_name), updated_at=now()`, [resolvedUserId, email || `${resolvedUserId}@invalid.local`, fullName || null]); const membershipId = `membership:${tenantId}:${resolvedUserId}:${companyId || "tenant"}`; const result = await this.db.query(`INSERT INTO ai.memberships (id,user_id,tenant_id,company_id,role,status) VALUES ($1,$2,$3,$4,$5,'invited') ON CONFLICT (user_id,tenant_id,company_id) DO UPDATE SET role=EXCLUDED.role,status='invited',version=ai.memberships.version+1,updated_at=now() RETURNING id AS membership_id,user_id,tenant_id,company_id,role,status,version`, [membershipId, resolvedUserId, tenantId, companyId, role]); const row = result.rows[0]; return { membership: { membershipId: row.membership_id, userId: row.user_id, tenantId: row.tenant_id, companyId: row.company_id, role: row.role, status: row.status, version: row.version, permissions: [...permissionsForRole(row.role)] }, reused: result.rowCount === 0 }; }
  async activateByUser({ userId }) { const result = await this.db.query("UPDATE ai.memberships SET status='active',version=version+1,updated_at=now() WHERE user_id=$1 AND status='invited' RETURNING id AS membership_id,user_id,tenant_id,company_id,role,status,version", [userId]); return result.rows.map((row) => ({ membershipId: row.membership_id, userId: row.user_id, tenantId: row.tenant_id, companyId: row.company_id, role: row.role, status: row.status, version: row.version, permissions: [...permissionsForRole(row.role)] })); }
  async update({ membershipId, tenantId, role, companyId, status, expectedVersion }) { const result = await this.db.query(`UPDATE ai.memberships SET role=COALESCE($3,role),company_id=COALESCE($4,company_id),status=COALESCE($5,status),version=version+1,updated_at=now() WHERE id=$1 AND tenant_id=$2 AND version=$6 RETURNING id AS membership_id,user_id,tenant_id,company_id,role,status,version`, [membershipId, tenantId, role || null, companyId === undefined ? null : companyId, status || null, expectedVersion]); if (!result.rowCount) { const current = await this.db.query("SELECT version FROM ai.memberships WHERE id=$1 AND tenant_id=$2", [membershipId, tenantId]); if (!current.rowCount) throw new MembershipNotFoundError(); return { conflict: { expectedVersion, actualVersion: current.rows[0].version } }; } const row = result.rows[0]; return { membership: { membershipId: row.membership_id, userId: row.user_id, tenantId: row.tenant_id, companyId: row.company_id, role: row.role, status: row.status, version: row.version, permissions: [...permissionsForRole(row.role)] }, reused: false }; }
  async revoke({ membershipId, tenantId, expectedVersion }) { return this.update({ membershipId, tenantId, expectedVersion, status: "revoked" }); }
}
module.exports = { MembershipNotFoundError, InMemoryMembershipStore, PostgresMembershipStore };
